
jobdocker:
  stage: build
  before_script:
    - docker info
  build:
    stage: build
    script:
      - export IMAGE_TAG=$(echo -en $CI_BUILD_REF_NAME | tr -c '[:alnum:]_.-' '-')
      - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
      - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
      - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
    tags:
      - shell
    only:
      - master
